### ISSUE TITLE
ImportError: cannot import name 'ZCA'

### ISSUE THREAD

**Issue by phonygene** [mwv/zca#3]
Got ImportError: cannot import name 'ZCA' after install in Anaconda3 virtual env.

Not compatible with python 3.6?

Any suggestion will be appreciated.

**Comment by smsubham** [comment]
Am getting the same error.
ImportError: cannot import name 'ZCA' from 'zca' (C:\Users\SubhamM\Anaconda3\lib\site-packages\zca-0.1.0-py3.7.egg\zca\__init__.py)

**Comment by tud111317** [comment]
If anyone else has this issue, check my fork: [https://github.com/tud111317/zca](url)

**Comment by mwv** [comment]
@tud111317 thanks. could you send a pull request. happy to merge in your improvements.

**Comment by mwv** [comment]
https://github.com/mwv/zca/pull/4 has fixed this.

Thanks @tud111317.
